### ISSUE TITLE
jq index string error

### ISSUE THREAD

**Issue by brokosz** [wilsongoode/covid-bitbar#4]
Using a similar config to the Read Me, I'm getting the following error both in bitbar and in terminal:

`jq: error (at <stdin>:0): Cannot index string with string "state"`

I confirmed `jq` is installed via brew. `jq-1.6`

**Comment by wilsongoode** [comment]
Seems like a syntax error with jq. Could you share your script so I can try to help you debug?

**Comment by brokosz** [comment]
oops - user error. I was using the 1.1 version from the bitbar repo. The 1.3 version here works a treat. Thanks for the response!
